services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"  # Replace 'app' with your Flask app's entry point
    autoDeploy: true